# Generated by Django 6.0.3 on 2026-03-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_pedido_numero_seguimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
