# Generated by Django 6.0.3 on 2026-03-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_itempedido_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
