# Generated by Django 6.0.3 on 2026-03-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_itempedido_precio_unitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarruselImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('subtitulo', models.TextField(blank=True, verbose_name='Subtítulo')),
                ('imagen', models.ImageField(upload_to='carrusel/', verbose_name='Imagen')),
                ('url', models.URLField(blank=True, verbose_name='URL de enlace')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Imagen del carrusel',
                'verbose_name_plural': 'Imágenes del carrusel',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
    ]
