# Generated by Django 6.0.3 on 2026-03-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_carruselimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='contenido_caja',
            field=models.JSONField(blank=True, default=dict, help_text="Contenido de la caja (ej: {'items': [{'producto_id': 1, 'cantidad': 10}]})"),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_caja',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de la caja (opcional, si es diferente al precio unitario x cantidad)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='venta_por_caja',
            field=models.BooleanField(default=False, help_text='¿Este producto se vende por caja?'),
        ),
    ]
